[PPS-169] Created Langugapack 2.0 on v14 for windows-x64
EnterpriseDB/edb-installers pull request #22
Opened 2021-07-01 13:46 UTC by moreparesh

- Build languagepack for Windows-x64 from v14 branch
Perl version 5.34
Python version 3.9
Tcl/TK version 8.6
Setuptools 57.0.0

2021-07-02 04:48 UTC, sandeep-edb requested changes
Paresh, can we use variables instead of hard-coding the versions in the script? Also, I don't see changes for LP variables in settings.sh.in in the patch. I guess that's also required?

2021-07-02 07:30 UTC, moreparesh commented
> Paresh, can we use variables instead of hard-coding the versions in the script? Also, I don't see changes for LP variables in settings.sh.in in the patch. I guess that's also required?

I have updated version.sh with TCL/TK version, also added place holder for python batch script. LP Variables added in setting.sh.in

2021-07-02 12:03 UTC, sandeep-edb approved these changes

2021-07-02 12:03 UTC, merged

2021-07-06 12:40 UTC, Semab-Tariq commented
Hi @moreparesh 

PG-14beta2 build is still failing while building with new LP and Perl-5.34 
Error is the same as mentioned in PPS-210